import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, ChefHat, Clock, PackageCheck, X } from "lucide-react";
import toast from "react-hot-toast";
import RestaurantSidebar from "../components/RestaurantSidebar.jsx";
import { useAuth } from "../context/AuthContext.jsx";
import { apiRequest } from "../lib/api.js";

const tabs = ["All", "Pending", "Preparing", "Ready", "Completed"];
const displayStatus = (status) => ({ pending: "Pending", confirmed: "Preparing", preparing: "Preparing", ready: "Ready", delivered: "Completed", cancelled: "Cancelled" }[status] || status);

export default function RestaurantOrders() {
  const { token } = useAuth();
  const [orders, setOrders] = useState([]);
  const [tab, setTab] = useState("All");
  const load = useCallback(async () => { try { const data = await apiRequest("/orders/", { token }); setOrders(data.results || data); } catch (error) { toast.error(error.message); } }, [token]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => orders.filter((order) => tab === "All" || displayStatus(order.status) === tab), [orders, tab]);
  const updateStatus = async (id, status) => { try { await apiRequest(`/orders/${id}/status/`, { token, method: "POST", body: { status } }); toast.success("Order status updated."); await load(); } catch (error) { toast.error(error.message); } };
  const counts = { pending: orders.filter((order) => order.status === "pending").length, preparing: orders.filter((order) => ["confirmed", "preparing"].includes(order.status)).length, ready: orders.filter((order) => order.status === "ready").length, completed: orders.filter((order) => order.status === "delivered").length };
  return <div className="min-h-screen bg-[#fffaf7]"><RestaurantSidebar /><main className="ml-72 min-h-screen p-8"><p className="text-sm text-gray-500">Order management</p><h1 className="mt-1 text-3xl font-bold">Restaurant Orders</h1><div className="mt-7 grid gap-4 md:grid-cols-4">{[["New orders", counts.pending, Clock], ["Preparing", counts.preparing, ChefHat], ["Ready", counts.ready, PackageCheck], ["Completed", counts.completed, Check]].map(([label, value, Icon]) => <div key={label} className="rounded-3xl border border-orange-100 bg-white p-5 shadow-sm"><Icon className="text-orange-500" /><p className="mt-3 text-sm text-gray-500">{label}</p><p className="text-3xl font-bold">{value}</p></div>)}</div><div className="mt-8 flex flex-wrap gap-3">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-full px-5 py-2 font-semibold ${tab === item ? "bg-orange-500 text-white" : "bg-white text-gray-600"}`}>{item}</button>)}</div><div className="mt-8 grid gap-5 xl:grid-cols-2">{filtered.map((order) => <article key={order.id} className="rounded-3xl border border-orange-100 bg-white p-6 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-bold">#{String(order.number).slice(0, 8).toUpperCase()}</h2><p className="mt-1 text-sm text-gray-500">{order.customer_detail?.first_name || "Customer"} · {new Date(order.created_at).toLocaleString()}</p></div><span className="rounded-full bg-orange-50 px-3 py-1 text-sm font-semibold text-orange-600">{displayStatus(order.status)}</span></div><p className="mt-5 text-sm text-gray-600">{order.items.map((item) => `${item.quantity} × ${item.name}`).join(", ")}</p><p className="mt-3 text-xl font-bold">₹{order.total}</p><div className="mt-5 flex gap-3 border-t pt-5">{order.status === "pending" && <><button onClick={() => updateStatus(order.id, "confirmed")} className="flex-1 rounded-xl bg-orange-500 px-4 py-3 font-semibold text-white">Accept order</button><button onClick={() => updateStatus(order.id, "cancelled")} className="rounded-xl bg-red-50 px-4 text-red-500"><X /></button></>}{["confirmed", "preparing"].includes(order.status) && <button onClick={() => updateStatus(order.id, "ready")} className="flex-1 rounded-xl bg-purple-500 px-4 py-3 font-semibold text-white">Mark ready</button>}{order.status === "ready" && <p className="rounded-xl bg-green-50 px-4 py-3 font-semibold text-green-700">Waiting for delivery partner</p>}</div></article>)}{!filtered.length && <p className="text-gray-500">No orders in this view.</p>}</div></main></div>;
}
